safetrustcr/backend-SafeTrust

- README.md
- metadata/databases/safetrust/tables/public_apartment_images.yaml
- metadata/databases/safetrust/tables/tables.yaml
- migrations/safetrust/1732401439975_run_sql_migration/down.sql
- migrations/safetrust/1732401439975_run_sql_migration/up.sql
Add new apartments images table.
Add new apartments images table.
- **Add here the changes**:
- Add new apartments images table.
- Create new table
- **More changes**:
N/A
Create table:
Add items:
Evidence add item:
Select evidence:
Update column in new table:
This pull request will **close #23 ** upon merging.
---
> feat: Add aparments images table

- Dockerfile
- docker-compose.yml
- hasura.sh
Add here some information
- **Add here the changes**:
- **More changes**:
- **Video**: [Link to Loom video](https://loom.com)
- **Video**: [Link to Loom video](https://loom.com)
This pull request will **close # [Issue Number]** upon merging.
---
> dockerize hasura command

- README.md
- docker-compose.yml
- metadata/databases/safetrust/tables/public_users.yaml
Integrates firebase authentication with hasura.
- Modify users table to include new roles anonymous, landlord and tenant.
- Integrate firebase authentication 
- Can't use authentication header to make queries
Closes https://github.com/safetrustcr/Backend/issues/22
---
> feat: add firebase auth integration

- seeds/safetrust/1733963959819_user_seed.sql
- seeds/safetrust/1733970410880_departments_seed.sql
Adding initial seeds 
N/A
N/A
N/A
N/A
---
> Feat: initial seeds

- seeds/safetrust/20241221112115_escrow_api_calls.sql
❗ Pull Request Information
This PR implements seed data for the escrow_api_calls table to simulate various API interactions with the escrow service. This data will help in testing, development, and demonstration of the system's functionality.
🌀 Summary of Changes
- Added SQL migration script: Created comprehensive seed data for escrow_api_calls table
- Implemented test scenarios: Added test data for various HTTP methods (GET, POST, PUT, DELETE)
- Added error scenarios: Included both client (400) and server (500) error cases
- Created time-sequenced data: Added timestamps spanning multiple days for realistic data distribution
- Added data validation: Ensured all data complies with table constraints and foreign key relationships
🛠 Testing
Evidence Before Solution:
Main issue: Lack of test …
> create seed script for escrow_api_calls table

- seeds/safetrust/1734721404143_escrow_xdr_transactions.sql
Add here some information
- **Add here the changes**:
- **More changes**:
- **Video**: [Link to Loom video](https://loom.com)
- **Video**: [Link to Loom video](https://loom.com)
This pull request will **close # [Issue Number]** upon merging.
---
> Feat: add seed script for escrow_xdr_transactions

- seeds/safetrust/1736373626060_user_wallet_seed.sql
This PR is for add the user_wallets seed this improve the experience at the moment to set up the backend generating data for the user_wallets table
- **Add here the changes**:
N/A
This pull request will close #50 upon merging.
---
> Feat: added user_wallet seed

- tests/karate/features/escrow_api_calls/escrow_api_calls.feature
❗ **Pull Request Information**  
This pull request implements comprehensive **Karate tests** for the `escrow_api_calls` table to verify functionality and ensure compliance with business rules and table constraints.  
- Added **Karate test scenarios** for the following operations:  
- Create escrow API call with required fields.  
- Query escrow API call by ID.  
- Update escrow API call details.  
- Delete escrow API call.  
- List all escrow API calls.  
- Implemented **negative test cases**:  
- Attempt to create escrow with invalid amount.  
- Attempt to get escrow status with an invalid ID.  
- Refactored and optimized **Karate configurations** for reusable components.  
- **Video**: [Before Solution Loom Video](https://loom.com)  
- **Video**: [After Solution Loom …
> [Backend] Implement Karate tests for escrow_api_calls table

- tests/karate/features/apartments/apartment_images.feature
❗ Pull Request Information
This PR is for fix apartment_images tests ensuring the correct functionality of them
🌀 Summary of Changes
Evidence After Solution:
📂 Related Issue
This pull request will close #99 upon merging.
> fix: fixed apartment_images tests

- docker-compose-test.yml
- tests/karate/features/apartments/apartment_images.feature
This PR is to fix the test apartment_images
> This PR closes: #101  issue
---
> Fix: aparment_images_test

- metadata/tenants/hotel_industry/databases/tables/public_rooms.yaml
- metadata/tenants/hotel_industry/databases/tables/public_rooms_readme.md
- metadata/tenants/hotel_industry/test_seed/public_room_seed.sql
This PR implements the `rooms` table for the `hotel_industry` tenant as part of our multi-tenant architecture. The table stores essential room details and establishes a foreign key relationship with the `hotels` table.  
- Added `rooms` table with fields: `room_id`, `hotel_id`, `room_number`, `room_type`, `price_night`, `status`, `capacity`, `created_at`, and `updated_at`.  
- Enforced constraints such as unique room numbers per hotel, foreign key relationships, and proper data validation.  
- Added indexing for optimized queries on `hotel_id` and `room_type`.  
- Updated metadata to track the table in Hasura.  
- Provided seed data and deployment scripts for easy setup.  
1. Run `./deploy-tenant.sh hotel_industry --admin-secret myadminsecretkey --endpoint "http://localhost:8082"`  
2. …
> feat(rooms): add rooms table for hotel_industry tenant

- config.yaml
- docker-compose.yml
- migrations/safetrust/1733171122100_forgot_password/down.sql
- migrations/safetrust/1733171122100_forgot_password/up.sql
- package.json
- webhook/Dockerfile
- webhook/forgot-password.js
- webhook/index.js
- webhook/package.json
- webhook/reset-password.js
- webhook/webhooks.js
This PR implements the backend functionality for the forgot password feature, providing secure endpoints for password reset operations. The implementation includes database migrations, API endpoints, and webhook handlers to manage the password reset flow securely.
- **Database Changes**:
- Added migration for password reset tokens
- Added new columns for token management and expiration
- Implemented down migration for rollback support
- **API Endpoints**:
- Added `/api/auth/forgot-password` endpoint for initiating reset
- Added `/api/auth/reset-password` endpoint for password update
- Added `/api/auth/validate-reset-token` endpoint for token verification
- Implemented rate limiting and security measures
- **Webhook Handlers**:
- Added `forgot-password.js` …
> feat: Forgot Password Functionality in User Authentication Flow

- tests/karate/features/apartments/apartment.feature
- tests/karate/features/apartments/apartment_images.feature
- tests/karate/features/apartments/create-apartment.feature
❗ Pull Request Information
This PR is for fix apartment_images tests ensuring the correct functionality of them
🌀 Summary of Changes
Evidence After Solution:
> fix: fixed apartment tests issues

- README.md
❗ *Pull Request Information*
This PR is for add the steps and information about multi-tenant architecture(data-base per tenant) in our metadata 
- *Add here the changes*:
This pull request will close #106  upon merging.
---
> Feat: Update README.md to add instructions for multi-tenant metadata

- migrations/hotel_industry/1745615873_update_hotels_table/down.sql
- migrations/hotel_industry/1745615873_update_hotels_table/up.sql
Update hotels table with required constraints and gen_random_uuid
> feat: Update hotels table with required constraints and gen_random_uuid

- migrations/hotel_industry/1746439500253_create-room-images/down.sql
- migrations/hotel_industry/1746439500253_create-room-images/up.sql
This PR implements the room-images table in the public schema . The table includes a UUID primary key, a UUID room_id, r, an image url and uploaded_at timestamp, along with indexing.
- **Added the migration files for room-image table**:
This pull request will **close # [143]** upon merging.
---
> Add migrations for room-images table

- migrations/hotel_industry/1745664202193_create_escrow_transaction_users/down.sql
- migrations/hotel_industry/1745664202193_create_escrow_transaction_users/up.sql
- seeds/hotel_industry/escrow_transaction_users.sql
Closes #136 
Implemented escrow_transaction_users
> escrow_transaction_users

- seeds/hotel_industry/hotels_seed.sql
This PR adds comprehensive seed data for the `hotels` table in the hotel industry module, providing realistic test data for development and testing purposes.
- **New file**: `seeds/hotel_industry/hotels_seed.sql`
- **Records added**: 15 hotel entries with diverse characteristics
- **Coverage**: Hotels across major Costa Rican regions plus one international entry
- **Central Valley**: 5 hotels (San José, Alajuela, Cartago)
- **Caribbean Coast**: 2 hotels (Limón, Puerto Viejo)
- **Pacific Coast**: 3 hotels (Puntarenas, Manuel Antonio, Playa Hermosa)
- **North Pacific**: 2 hotels (Guanacaste region)
- **Northern Zone**: 2 hotels (La Fortuna, Sarapiquí)
- **International**: 1 hotel (São Paulo, Brazil)
- Business hotels
- Eco-lodges
- Beach resorts
- Mountain retreats
- Boutique hotels
- …
> Create database seeds for hotels table

- metadata/base/actions.graphql
- metadata/base/actions.yaml
- migrations/hotel_industry/1745664202192_create_escrow_transactions/up.sql
- webhook/index.js
- webhook/prepare-escrow-contract.js
This PR implements the escrow contract preparation endpoint for the hotel_industry tenant.
- Adds `escrow_payload` JSONB column to `escrow_transactions` for the hotel_industry tenant
- Defines and implements the Hasura Action `prepare_escrow_contract`
- Implements webhook logic to receive, validate, and store escrow contract payloads as per TrustlessWork API schema
- Returns the correct response with `id`, `engagementId`, and the full payload
- The escrow creation form is already available in the frontend.
- However, the backend has no endpoint to handle or persist the TrustlessWork API schema.
- Critical escrow data (roles, title, amount, etc.) is not yet stored in the database.
1. Run the stack with `docker compose up --build`
2. Deploy metadata and …
> Feat: Prepare escrow deploy endpoint for TrustlessWork integration

- metadata/tenants/hotel_industry/databases/functions/get_top_rooms_by_reservations.yaml
- migrations/hotel_industry/1756195007000_create_top_rooms_function/down.sql
- migrations/hotel_industry/1756195007000_create_top_rooms_function/up.sql
- tests/karate/features/hotels/top_rooms_function.feature
- Create PostgreSQL function to identify top 5 most reserved rooms
- Support time period filtering (week, month, year, all)
- Support reservation status filtering
- Return room details with reservation counts and total revenue
- Include proper error handling and performance optimization
- Add comprehensive e2e tests using Karate framework
- Add Hasura metadata for GraphQL exposure
Resolves #141
> feat: add top 5 rooms function

- metadata/tenants/safetrust/databases/tables/pricing_rules/pricing_rules.yaml
- migrations/safetrust/1756344655_create_pricing_rules/down.sql
- migrations/safetrust/1756344655_create_pricing_rules/up.sql
Closes #190 
This pull request introduces the **`safetrust.pricing_rules`** table as the foundation for our Hybrid Architecture implementation.  
The table ensures that the **SafeTrust tenant** has full pricing autonomy, eliminating cross-schema dependencies and simplifying our **multi-tenant architecture** for MVP demonstration.
- Created `pricing_rules` table under the `safetrust` schema.
- Applied migrations via Hasura for consistent schema management.
- Verified integration in Hasura Console → Data tab.
- Ensured the table is available for use in application logic.
- Establishes **tenant-specific pricing rules** for SafeTrust.
- Removes reliance on shared or cross-schema configurations.
- Paves the way for **scalable and independent tenant management**.
> feat: Create SafeTrust pricing rules table for hybrid architecture

- metadata/tenants/hotel_industry/databases/tables/hotel_industry_pricing_rules.yaml
- metadata/tenants/hotel_industry/databases/tables/tables.yaml
- migrations/hotel_industry/1756285113000_create_pricing_rules/down.sql
- migrations/hotel_industry/1756285113000_create_pricing_rules/up.sql
- seeds/hotel_industry/10_pricing_rules_seed.sql
and associated migrations, permissions, and seed data
Closes #194
> feat: add hotel industry pricing rules table 

- handlers/auth/test-user-sync.js
- handlers/auth/user-sync-routes.js
- handlers/auth/user-sync.js
- package.json
> feat(auth): implement user database synchronization

- handlers/auth/auth-middleware.js
Closes #206
**Summary**
* Added role-based JWT claims for Hasura (`tenant | landlord | admin`) 🏷️
* Integrated Firebase custom claims + token verification 🔗
* Implemented helpers:
* `requireRole` (auth middleware) ✅
* `setCustomClaims`, `updateUserRole`, `ensureHasuraClaims` 🔄
* `verifyFirebaseToken` (Hasura-ready verification) 🔑
* Standardized error codes/messages in `ALL_CAPS_FORMAT` 📢
**Result**
Now Hasura enforces **secure role-based access** with Firebase-issued tokens ⚡🔥
> feat(auth) :: Implemented custom JWT claims system for Hasura GraphQL
